import { labelClassificationLine, labelEntityActive } from "../../lib/displayLabels.js";

export const KB_ENTITIES = {
  phrases: {
    key: "phrases",
    title: "Формулировки",
    apiBase: "/api/admin/phrases",
    idKey: "id",
    listPrimary: (i) => i.phrase_text,
    listSemantic: (i) => labelClassificationLine(i.scenario, i.sentiment, i.priority),
    listPreview: (i) => (i.phrase_text || "").slice(0, 140),
    isActive: (i) => i.is_active,
    fields: [
      { key: "phrase_text", label: "Фраза", type: "textarea", required: true },
      { key: "scenario", label: "Сценарий", type: "text" },
      { key: "sentiment", label: "Тональность", type: "text" },
      { key: "priority", label: "Приоритет", type: "text" },
      { key: "is_active", label: "Активна", type: "checkbox" },
    ],
    defaults: { phrase_text: "", scenario: "", sentiment: "", priority: "", is_active: true },
  },
  templates: {
    key: "templates",
    title: "Шаблоны",
    apiBase: "/api/admin/templates",
    idKey: "id",
    listPrimary: (i) => i.title,
    listSemantic: (i) => labelClassificationLine(i.scenario, i.sentiment, i.priority),
    listPreview: (i) => (i.template_text || "").slice(0, 140),
    isActive: (i) => i.is_active,
    fields: [
      { key: "title", label: "Название", type: "text", required: true },
      { key: "scenario", label: "Сценарий", type: "text" },
      { key: "sentiment", label: "Тональность", type: "text" },
      { key: "priority", label: "Приоритет", type: "text" },
      { key: "template_text", label: "Текст шаблона", type: "textarea", required: true },
      { key: "is_fallback", label: "Fallback", type: "checkbox" },
      { key: "is_active", label: "Активен", type: "checkbox" },
    ],
    defaults: {
      title: "",
      scenario: "",
      sentiment: "",
      priority: "",
      template_text: "",
      is_fallback: false,
      is_active: true,
    },
  },
  scenarios: {
    key: "scenarios",
    title: "Сценарии",
    apiBase: "/api/admin/scenarios",
    idKey: "id",
    listPrimary: (i) => `${i.code} — ${i.title || ""}`.trim(),
    listSemantic: (i) => labelEntityActive(i.is_active),
    listPreview: (i) => (i.description || "").slice(0, 140),
    isActive: (i) => i.is_active,
    fields: [
      { key: "code", label: "Код", type: "text", required: true, readonlyOnEdit: true },
      { key: "title", label: "Название", type: "text", required: true },
      { key: "description", label: "Описание", type: "textarea" },
      { key: "is_active", label: "Активен", type: "checkbox" },
    ],
    defaults: { code: "", title: "", description: "", is_active: true },
  },
  sentiments: {
    key: "sentiments",
    title: "Тональности",
    apiBase: "/api/admin/sentiments",
    idKey: "id",
    listPrimary: (i) => `${i.code} — ${i.title || ""}`.trim(),
    listSemantic: (i) => labelEntityActive(i.is_active),
    listPreview: (i) => (i.description || "").slice(0, 140),
    isActive: (i) => i.is_active,
    fields: [
      { key: "code", label: "Код", type: "text", required: true, readonlyOnEdit: true },
      { key: "title", label: "Название", type: "text", required: true },
      { key: "description", label: "Описание", type: "textarea" },
      { key: "is_active", label: "Активен", type: "checkbox" },
    ],
    defaults: { code: "", title: "", description: "", is_active: true },
  },
};

