ALTER TABLE interaction_scenarios ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE sentiment_profiles ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE sentiment_profiles ADD COLUMN IF NOT EXISTS description TEXT;

ALTER TABLE response_templates ADD COLUMN IF NOT EXISTS title VARCHAR(255);
ALTER TABLE response_templates ADD COLUMN IF NOT EXISTS is_fallback BOOLEAN NOT NULL DEFAULT FALSE;
